### PR TITLE
Create calendar ruby

### LINKED ISSUE #16: Using Nylas Ruby v3 SDK, create a code sample to create calendar
Using Nylas Ruby v3 SDK, create a code sample to create calendar

### PR DESCRIPTION
**Pull request by sharsha315**
## PR Acceptance Criteria

Fixes #16 

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [ ] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR labels added

### CODE REVIEW

**Review by atejada — COMMENTED** [review]
@sharsha315 You're missing the **request_body** parameter. You cannot create an empty calendar 😊

**Comment by sharsha315** [comment]
Hi @atejada, @relaxedtomato, I have updated the code with request_body parameter as per your suggestion. Kindly review the changes and provide feedback. Thank you.

**Review by atejada — APPROVED** [review]
All good 👍

**Comment by atejada** [comment]
Congratulations @sharsha315 This PR has been merged 😎

**Pull request merged**
