### PR TITLE
Created calendar using Kotlin/Java SDK

### LINKED ISSUE #62: Using Nylas Kotlin v3 SDK, create a code sample to create calendar event
Using Nylas Kotlin v3 SDK, create a code sample to create calendar event

### PR DESCRIPTION
**Pull request by NikhilTaneja98**
## PR Acceptance Criteria
Fixes #62 

## Guidelines
* [ ] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [ ] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [ ] A `README.md` available describing how to setup and test the code?
* [ ] The code sample in the correct location (i.e. `calendar/java/create-calendar`)?
* [ ] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [ ] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

### CODE REVIEW

**Review by atejada — COMMENTED** [review]
@NikhilTaneja98 This line need to be fixed 😉 

```
import com.nylas.CreateCalendarRequest
```

It's missing *models*

**Comment by NikhilTaneja98** [comment]
@atejada My mad, made the changes.

**Review by atejada — APPROVED** [review]
All good 👍

**Comment by atejada** [comment]
Congratulations @NikhilTaneja98 Your PR has been merged 😄

**Comment by NikhilTaneja98** [comment]
@atejada this PR is not labeled as hacktoberfest-accepted. It will be considered as a valid PR?

**Comment by relaxedtomato** [comment]
@NikhilTaneja98 - just added!

**Comment by atejada** [comment]
Thanks @relaxedtomato 👍 sorry @NikhilTaneja98 😅

**Pull request merged**
