### PR TITLE
add "calendar event delete" code sample

### PR DESCRIPTION
**Pull request by aakzsh**
## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR labels added

### CODE REVIEW

**Comment by aakzsh** [comment]
fixes #46

**Comment by relaxedtomato** [comment]
Hi @aakzsh - will get this reviewed shortly, that's for posting our first PR of hackatoberfest!

**Comment by atejada** [comment]
Thanks @aakzsh I'm going to merge your PR 🥳 Feel free to request another PR 😊

**Review by atejada — COMMENTED** [review]
All good. Tested and working as expected.

**Comment by aakzsh** [comment]
cool thanks! And sure ill look into submitting more PRs

**Pull request merged**
