### PR TITLE
feat: read webhook with nylas python sdk

### LINKED ISSUE #53: Using Nylas Python v3 SDK, create a code sample to read webhook
Using Nylas Python v3 SDK, create a code sample to read webhook

### PR DESCRIPTION
**Pull request by Onwuagba**
## PR Acceptance Criteria
Fixes #53 

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR labels added

### CODE REVIEW

**Review by atejada — COMMENTED** [review]
@Onwuagba This code is for V2 and you need to use V3. Check this for more information https://nylas-python-sdk-reference.pages.dev/reference/resources/webhooks/

**Comment by Onwuagba** [comment]
@atejada Can I get profiled on V3 to test the application? I sent a mail to the devrel address and have no got a response yet.

**Comment by atejada** [comment]
@Onwuagba Have you reset your password on the V3 dashboard? Have you created your API Keys and Grant?

**Comment by Onwuagba** [comment]
@atejada Yes, I have reset the password and have created the API Key as well as the Grant. Is there something I'm may be missing as I followed the doc shared in your previous response?

**Review by atejada — APPROVED** [review]
@Onwuagba Sorry it took me long...needed to setup my Webhooks server in order to fully test your PR...all good now...going to merge it 😉

**Pull request merged**
