### PR TITLE
feat: Add a Send Event RSVP Response Sample with check event particip…

### PR DESCRIPTION
**Pull request by navascogt**
…ant status

The README.md file was copied from other sample v2, modified for Send Event RSVP Response Setup, pointing to SDK v3 Documentation and general blog page because not found blog for this case.

resolves: #56

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR labels added

### CODE REVIEW

**Review by atejada — APPROVED** [review]
While it would be nice to had the option to choose "yes | no | maybe" at runtime, the code works as expected 😎

**Comment by atejada** [comment]
Thanks @navascogt I'm going to merge your PR 🥳 Feel free to request another PR 😊

**Comment by navascogt** [comment]
Hi @atejada , excellent, thank very much for the opportunity!!!

For sure next week, I will be taking other issues.

Regarding your suggestion, in the code was not committed, but I need to write for-loop in calendars then events in order to read the event ID to update, because maybe all of this is do managed in another issues I decide not to include it . But, as per suggestion I will add to prompt for the yes|no|maybe via input.  

Because this PR was already accepted (thanks again) what would you recommend me to follow?  I can create another branch and PR? What is your standard or methodology in order to do that?

**Comment by atejada** [comment]
No worries, it was just a suggestion to make your code better 😄 We asked for RSVP and you did that, so you're good to go 😌

**Comment by navascogt** [comment]
Hi @atejada @relaxedtomato wishing all is doing well, do you know why this issue was excluded from the Hacktoberfest ?

**Comment by atejada** [comment]
@navascogt What do you mean removed? It was merged...and I close it as it completed by you.

**Comment by relaxedtomato** [comment]
> wishing all is doing well, do you know why this issue was excluded from the Hacktoberfest ?

Also @navascogt - we marked the PR as `hacktoberfest-accepted`, is there any reason why you think it was excluded from Hacktoberfest?

**Comment by navascogt** [comment]
Thanks @relaxedtomato , yes, all you do were well, but in the Hacktoberfest site is marked by them as "excluded":

image

and clicking the question mark said:

image

**Comment by navascogt** [comment]
Even thought this issue is accepted or not, I want to continue contributing with another issues in October and after the Hacktoberfest, I want to learn more about Nylas and planning start using the free account in my personal app.

**Comment by relaxedtomato** [comment]
@navascogt - thanks for sharing this, looking forward to more contributions as we take a look into this.

**Comment by ashryanbeats** [comment]
That's bizarre. Sorry you ran into that @navascogt ! We really appreciate you're contributions and we'll try to figure out what happened.

**Comment by navascogt** [comment]
Thanks @ashryanbeats !!!

**Comment by relaxedtomato** [comment]
Hi @navascogt - the good news is that all contributions to `nylas-hacktoberfest-2023` will count towards Hackatoberfest 2023 🎉 

Our repository was blocked by mistake and it has been reverted.

**Comment by navascogt** [comment]
Thanks for validating and confirming @relaxedtomato , what a good news!!!

**Pull request merged**
