### PR TITLE
 Implement update calendar func

### PR DESCRIPTION
**Pull request by wiseaidev**
## PR Acceptance Criteria
Related to #42 

## Guidelines
* [X] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [X] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [X] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [X] A `README.md` available describing how to setup and test the code?
* [X] The code sample in the correct location (i.e. `calendar/python/update_calendar`)?
* [ ] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

P.S. As always, I am using poetry because life is poetry ;-)

### CODE REVIEW

**Comment by atejada** [comment]
Hello @wiseaidev I send you an email with the details on how to finish setting up your V3 account. Once you do that, please update your source code so that it can be tested and accepted.

**Comment by wiseaidev** [comment]
Done!

**Review by atejada — APPROVED** [review]
All good 👍

**Comment by atejada** [comment]
Congratulations @wiseaidev I'm merging this PR

**Pull request closed without merging**
