### PR TITLE
Implement read calendar func

### PR DESCRIPTION
**Pull request by wiseaidev**
## PR Acceptance Criteria
Related to #39 

## Guidelines
* [X] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [X] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [X] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [X] A `README.md` available describing how to setup and test the code?
* [X] The code sample in the correct location (i.e. `calendar/python/read_calendar`)?
* [ ] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [ ] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

P.S. I am using poetry because life is poetry ;-)

### CODE REVIEW

**Comment by atejada** [comment]
Hello @wiseaidev I send you an email with the details on how to finish setting up your V3 account. Once you do that, please update your source code so that it can be tested and accepted.

**Comment by wiseaidev** [comment]
Hey @atejada. After conducting some research, I've come to the realization that there are two distinct versions of the dashboard, namely, v2 and v3. It appears that I am currently utilizing v2. Nevertheless, I find myself a bit uncertain about the process for accessing the v3 dashboard. Is there a distinct URL for it, separate from [dashboard.nylas.com](https://dashboard.nylas.com/)? Furthermore, I'm also unsure about how to reset my password, in accordance with the instructions provided in the email I received. Despite having submitted a password reset request through the "forgot password" page, I haven't received any email in response.

image

Looking forward to your response regarding this matter.

**Comment by wiseaidev** [comment]
Done!

**Comment by wiseaidev** [comment]
I deleted this branch by mistake:

```sh
git push origin read_calendar_events -d
```

New PR in  #89

**Pull request closed without merging**
