### PR TITLE
"create a code sample to create calendar" #3

### PR DESCRIPTION
**Pull request by kelbri10**
## PR Acceptance Criteria

Addresses Issue: #3 

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

### CODE REVIEW

**Comment by kelbri10** [comment]
Hopefully I configured the Github codespaces properly. It's my first time really working with that feature on Github. :) 

Look forward to any feedback you may have :D Thank you for trusting me with the issue it was fun to resolve. @relaxedtomato

**Comment by relaxedtomato** [comment]
@kelbri10 this looks awesome, before we merge, can we do the following:
- [ ]  include a `package.json` with the relevant packages

That's awesome you got a chance to work with Github Codespaces :)

**Comment by kelbri10** [comment]
Just updated with the `package.json` ! @relaxedtomato

**Comment by relaxedtomato** [comment]
@kelbri10 - PR is merged, feel free to take a look at other open tickets and reach out if you have any questions, you are already onboarded onto Nylas :)

**Pull request merged**
