### PR TITLE
add "calendar event read" code sample

### PR DESCRIPTION
**Pull request by aakzsh**
## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

### CODE REVIEW

**Comment by aakzsh** [comment]
fixes #45

**Comment by atejada** [comment]
@aakzsh You need to make sure your handling all possible "dates". You need to check "event.when.object" as we have "timespan", "datespan" and "date". You script will crash if you try to print "date" when it is actually a time or date span.

**Comment by aakzsh** [comment]
I see, you're correct! I'll make the necessary changes for it to handle all cases

**Comment by relaxedtomato** [comment]
@atejada - is this PR ready to review/merge?

**Review by atejada — APPROVED** [review]
Perfect! 👍

**Comment by atejada** [comment]
Merging 😎

**Pull request merged**
