### PR TITLE
Create webhook test

### LINKED ISSUE #52: Using Nylas Python v3 SDK, create a code sample to create webhook
Using Nylas Python v3 SDK, create a code sample to create webhook

### PR DESCRIPTION
**Pull request by sharsha315**
## PR Acceptance Criteria

Fixes #52 

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CONTRIBUTION.md)?
* [ ] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2023/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x] A `README.md` available describing how to setup and test the code?
* [x] The code sample in the correct location (i.e. `email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [x] Purpose of code sample is clear
* [x] The code sample is readable
* [x] Steps try out the code are provided
* [x] Code sample runs on codespaces environment
* [x] Code works as expected
* [x] PR labels added

### CODE REVIEW

**Review by atejada — CHANGES_REQUESTED** [review]
@sharsha315 All good, but please add a print after you create the webhook, so the information can be visible. 

Also, on the readme can you add that the callback_url needs to be in the following format:

```
https//xxx.com/webhooks
```

After those changes are implemented, I will merge this PR 😉

**Comment by sharsha315** [comment]
Hi @atejada and @relaxedtomato, I have made the requested necessary changes, please do review for the changes submitted and provide feedback if any. Thank you.

**Review by atejada — APPROVED** [review]
@sharsha315 Perfect! Thank you 😊 This is going to be merged 👍

**Comment by sharsha315** [comment]
Thank you @atejada, It could not have been completed without your support
and guidance.

**Pull request merged**
